# Research and Apply Pandas Data Structures

**Objective:** Understand the fundamental data structures in Pandas and learn how to access, inspect, and manipulate data.

This notebook contains the research explanations, a practical Python implementation, and outputs demonstrating the required Pandas operations.

## Part 1: Research

### 1. What is Pandas, and why is it used in data analysis?

Pandas is a Python library used to work with structured data. It makes it easier to organize, clean, filter, analyze, and summarize information stored in tables. It is widely used in data analysis because it provides convenient tools for handling missing values, selecting data, combining datasets, and calculating statistics.

### 2. What is a Pandas Series?

A Series is a one-dimensional labeled data structure in Pandas. It stores a sequence of values and gives each value an index label. A Series can hold data such as numbers, text, or dates. It is similar to a single column in a table.

### 3. What is a Pandas DataFrame?

A DataFrame is a two-dimensional table made of rows and columns. Each column can have its own data type, such as text, integers, or decimal numbers. DataFrames are useful for storing and analyzing datasets because we can select rows and columns, filter records, and calculate summaries.

### 4. What is the difference between `loc[]` and `iloc[]`?

`loc[]` selects data using row and column labels. For example, `df.loc[0, "Name"]` selects the value in the row labeled `0` and the column named `"Name"`.

`iloc[]` selects data using integer positions, starting from zero. For example, `df.iloc[0, 1]` selects the value in the first row and second column.

A key difference is that `loc[]` uses labels, while `iloc[]` uses positions.

### 5. Explain the purpose of `head()`, `tail()`, `info()`, and `describe()`.

- `head()` displays the first rows of a DataFrame. By default, it shows five rows.
- `tail()` displays the last rows of a DataFrame. By default, it shows five rows.
- `info()` prints a concise overview, including the number of rows, column names, non-null values, data types, and memory usage.
- `describe()` generates descriptive statistics for numeric columns, such as count, mean, standard deviation, minimum, quartiles, and maximum.

## Part 2: Practical Application

### 1. Import Pandas and create a DataFrame with at least 10 records

The dataset below contains information about 10 students, including their names, ages, departments, and exam scores.

In [1]:
import pandas as pd

data = {
    "Name": ["Mona", "Omar", "Salma", "Youssef", "Nour",
             "Ali", "Farah", "Adam", "Laila", "Ziad"],
    "Age": [20, 21, 20, 22, 19, 21, 20, 23, 19, 22],
    "Department": ["Computer", "Electronics", "Communications", "Computer",
                   "Electronics", "Communications", "Computer", "Electronics",
                   "Communications", "Computer"],
    "Score": [88, 76, 95, 67, 91, 73, 84, 59, 97, 80]
}

df = pd.DataFrame(data)
df

      Name  Age      Department  Score
0     Mona   20        Computer     88
1     Omar   21     Electronics     76
2    Salma   20  Communications     95
3  Youssef   22        Computer     67
4     Nour   19     Electronics     91
5      Ali   21  Communications     73
6    Farah   20        Computer     84
7     Adam   23     Electronics     59
8    Laila   19  Communications     97
9     Ziad   22        Computer     80

### 2. Display the first five and last five records

Use `head()` for the first five records and `tail()` for the last five records.

In [2]:
print("First five records:")
display(df.head())

print("Last five records:")
display(df.tail())

First five records:

      Name  Age      Department  Score
0     Mona   20        Computer     88
1     Omar   21     Electronics     76
2    Salma   20  Communications     95
3  Youssef   22        Computer     67
4     Nour   19     Electronics     91

Last five records:

    Name  Age      Department  Score
5    Ali   21  Communications     73
6  Farah   20        Computer     84
7   Adam   23     Electronics     59
8  Laila   19  Communications     97
9   Ziad   22        Computer     80

### 3. Display the DataFrame's shape, column names, and data types

- `shape` returns a tuple in the form `(number_of_rows, number_of_columns)`.
- `columns` lists the column names.
- `dtypes` shows the data type of each column.
- `info()` gives a more complete overview of the DataFrame.

In [3]:
print("Shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())
print("\nData types:")
print(df.dtypes)
print("\nDataFrame information:")
df.info()

Shape: (10, 4)

Column names:
['Name', 'Age', 'Department', 'Score']

Data types:
Name          object
Age            int64
Department    object
Score          int64
dtype: object

DataFrame information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     object
 1   Age         10 non-null     int64
 2   Department  10 non-null     object
 3   Score       10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

### 4. Select specific rows and columns using `loc[]` and `iloc[]`

The examples below select the same general kind of information in two different ways: by labels with `loc[]`, and by integer positions with `iloc[]`.

In [4]:
# loc[]: select rows by index labels and columns by column names
print("Using loc[]: rows labeled 1 to 3, columns Name and Score")
display(df.loc[1:3, ["Name", "Score"]])

# iloc[]: select rows and columns by integer positions
print("Using iloc[]: rows at positions 1 to 3 (3 is excluded), columns at positions 0 and 3")
display(df.iloc[1:4, [0, 3]])

Using loc[]: rows labeled 1 to 3, columns Name and Score

      Name  Score
1     Omar     76
2    Salma     95
3  Youssef     67

Using iloc[]: rows at positions 1 to 3 (3 is excluded), columns at positions 0 and 3

      Name  Score
1     Omar     76
2    Salma     95
3  Youssef     67

### 5. Generate and interpret a statistical summary using `describe()`

`describe()` summarizes the numeric columns. The output helps us understand the distribution of students' ages and scores.

In [5]:
summary = df.describe()
summary

             Age      Score
count  10.000000  10.000000
mean   20.700000  81.000000
std     1.337494  12.382784
min    19.000000  59.000000
25%    20.000000  73.750000
50%    20.500000  82.000000
75%    21.750000  90.250000
max    23.000000  97.000000

### Interpretation of `describe()`

- **count:** There are 10 values in both the Age and Score columns.
- **mean:** The average age is 20.7 years, and the average score is 81.0.
- **std:** This shows how spread out the values are around the mean. A larger standard deviation means more variation.
- **min / max:** Ages range from 19 to 23, while scores range from 59 to 97.
- **25%, 50%, and 75%:** These are quartiles. The 50% value is the median, meaning half of the values are at or below it and half are at or above it.

**Conclusion:** Pandas makes it straightforward to store tabular data, inspect its structure, select particular records, and summarize numerical values.